### ISSUE TITLE
Store screenshots in CircleCI artifacts for failing system specs

### ISSUE THREAD

**Issue by blocknotes** [solidusio/solidus_starter_frontend#118]
Failing system specs don't use `capybara-screenshot` to store the screenshots but they are automatically generated by Rails. But `ScreenshotHelper` has no options to set the output path.

Perhaps we could update the Solidus orb in this way:
https://github.com/solidusio/circleci-orbs-extensions/pull/34/files

**Comment by elia** [comment]
Should be fixed by https://github.com/solidusio/circleci-orbs-extensions/releases/tag/v0.4.1
