### ISSUE TITLE
No filters in the sidebar for clothing taxon

### ISSUE THREAD

**Issue by blocknotes** [solidusio/solidus_starter_frontend#128]
Sidebar filters (PRICE RANGE) disappear when in clothing taxon.

---

When in caps taxon (http://localhost:3000/t/categories/caps) (or any taxon different from clothing), I see:
![image](https://user-images.githubusercontent.com/6893256/99085556-a06b3700-25c8-11eb-94c3-c9b80ab928ec.png)

---

When in clothing taxon (http://localhost:3000/t/categories/clothing), I see:
![image](https://user-images.githubusercontent.com/6893256/99085743-dd372e00-25c8-11eb-96b8-78304a86fb9f.png)
(neither at the bottom of the page)

**Comment by aleph1ow** [comment]
@blocknotes @kennyadsl 
I verified that solidus frontend behaves the same way. Should we close this or leave it here as a future improvement?

**Comment by blocknotes** [comment]
> @blocknotes @kennyadsl
> I verified that solidus frontend behaves the same way. Should we close this or leave it here as a future improvement?

Thanks @aleph1ow - I set it as Enhancement.

**Comment by fthobe** [comment]
@jarednorman 

I can confirm this has been fixed: 
![Uploading Screenshot 2024-12-05 at 15.20.14.png…]()
