### ISSUE TITLE
unRESTful OrdersController

### ISSUE THREAD

**Issue by RyanofWoods** [solidusio/solidus_starter_frontend#163]
Me and @kennyadsl have discussed this a little bit in Solidus PRs [4102][PR#4102] and [4081][PR#4081]. So I thought it would be a good idea to consolidate the information and let discussion about it happen here for easier reference in the future.

The `OrdersController` currently has the following methods that make it unRESTful:
- `populate` (can be moved to `OrderContentsController` like Solidus [PR 4102][PR#4102] that would it fix Solidus frontend)
- `populate_redirect` (discussed in Solidus [PR 4081][PR#4081] that it doesn't give much value. Could be good maybe to remove it)
- `empty` (can be moved to `OrderContentsController`)
- `accurate_title` (can become a private method)

[PR#4081]: https://github.com/solidusio/solidus/pull/4081
[PR#4102]: https://github.com/solidusio/solidus/pull/4102

The method `update` also currently has two responsibilities:
1. update the `@order.contents` after submitting an edit cart form by clicking "update" or "checkout"
2. advance the `order`'s state if the "checkout" button gets clicked and it's current `state` is `cart` (essentially start the checkout process)

This brings light to point worth discussing. If `OrderContentsController` was to be added and have the methods `create` and `destroy` which would respectively replace `OrdersControllers` `populate` and `empty`, the `OrdersController` wouldn't be truly RESTful and still would have multiple responsibilities. To achieve this the updating of `@orders.content` in `update`  would have to be moved to `OrdersContentsController`. But currently on the cart page, both the "update" and "checkout" buttons act as save buttons for the edit cart form. Moving the update content functionality out would cause the "checkout" to longer be able to save the content changes.

Another point that would be nice to discuss is, if we make it RESTful, what would be the most desirable routes for both of these controllers? Keeping the `cart` route would be nice, but how should we handle the `orders.content`?

Here's the different routes paths we would need:
```ruby
post '/orders/content', to: 'order_contents#create'
get '/cart', to: 'order_contents#edit', as: :cart
patch '/orders/content', to: 'order_contents#update', as: :update_order_content
delete '/orders/content', to: 'order_contents#destroy'

patch '/cart', to: 'orders#update', as: :update_cart
```

**Comment by fthobe** [comment]
@jarednorman PR #250 solves that
