### ISSUE TITLE
Deletion of old shared views

### ISSUE THREAD

**Issue by aleph1ow** [solidusio/solidus_starter_frontend#30]
- [x] `spree/shared/nav_bar` could be deleted but in turn it renders:

- [x] `spree/shared/locale_selector`: we don't render it actually in our header. I think we should do it instead. (Or is it part of the super basic approach?) (see #72 )

- [ ] `spree/shared/_login_bar_items`: This partial just contains a comment that says:
"solidus_auth_devise or a custom auth system can replace this partial".
Also, in this case, should we render it elsewhere?

**Comment by dinohamzic** [comment]
The majority of the work here is done, but we should double check the `shared` folder.

**Comment by fthobe** [comment]
Can be closed @jarednorman
