### ISSUE TITLE
Allow to set Last URL via URL parameter

### ISSUE THREAD

**Issue by fthobe** [solidusio/solidus_starter_frontend#391]
**Desired Behavior**
In certain use cases it makes sense to provide a return url via login parameter. Examples are: 
- request for review via email (reviews require in the current form a registration)
- return to other functionalities that were initially navigated to that are located behind a login wall

The ideal way would be to set the return url in a url parameter and make it agnostic to any future usage. 
https://example.com/orders would redirect unlogged users to https://example.com/login?url=/orders and set the url parameter. 

**Current Behavior**
There's no way to set the devise last_url via parameter requiring manual setting of the session redirect url.

**Comment by jarednorman** [comment]
This isn't a frontend thing, it's a solidus_auth_devise thing. Exposing the ability to redirect to arbitrary paths has security consequences, so it's better to do this on a case-by-case basis and use the [built-in support for post-login redirects](https://github.com/search?q=repo%3Asolidusio%2Fsolidus_auth_devise+return_to&type=code).

**Comment by fthobe** [comment]
> This isn't a frontend thing, it's a solidus_auth_devise thing. Exposing the ability to redirect to arbitrary paths has security consequences, so it's better to do this on a case-by-case basis and use the [built-in support for post-login redirects](https://github.com/search?q=repo%3Asolidusio%2Fsolidus_auth_devise+return_to&type=code).

Hey thanks! That’s of big help!
