### ISSUE TITLE
[Redesign] Header (mobile version)

### ISSUE THREAD

**Issue by aleph1ow** [solidusio/solidus_starter_frontend#68]
The mobile version of the header needs a redesign.
LOGIN / MY ACCOUNT and CART() could be replaced by icons.

| Signed Out | Signed In |
| -- | -- |
|<img width="373" alt="87171229-aecfdc00-c2d2-11ea-89c6-efdaf6f5fc9c" src="https://user-images.githubusercontent.com/3853105/90234951-cdb91500-de20-11ea-8d29-d7253824be3b.png">|<img width="374" alt="87171218-aaa3be80-c2d2-11ea-89b7-0e2533de9378" src="https://user-images.githubusercontent.com/3853105/90234955-cf82d880-de20-11ea-942c-744eff512a59.png">|

N.B. The **search by category** selector is there but is actually hidden. 
Is the search by category functionality still wanted?
Does the searchbar require a round of redesign too?
<img width="499" alt="Screenshot 2020-08-14 at 11 26 35" src="https://user-images.githubusercontent.com/3853105/90235230-3e603180-de21-11ea-8fa4-328adecb1cf8.png">

**Comment by fthobe** [comment]
@jarednorman  Can be closed
