### ISSUE TITLE
Check the components behaviour with cache server enabled

### ISSUE THREAD

**Issue by blocknotes** [solidusio/solidus_starter_frontend#79]
An example is in categories page using `bin/rails dev:cache`.
After the first visit the partial "Shop by Categories" seems to be cached and the current category is not highlighted anymore.

Image:
![image](https://user-images.githubusercontent.com/6893256/89025225-c07f2f00-d326-11ea-9b5f-bb9ea1e253c2.png)

Without cache the current category is in bold.

**Comment by fthobe** [comment]
@jarednorman can be closed
